#!/usr/bin/expect -f
set timeout 60
set cmd [lindex $argv 0]
if {[info exists env(SERVER_PASS)]} {
    set pass $env(SERVER_PASS)
} else {
    set pass ""
}
if {[info exists env(SERVER_HOST)]} {
    set host $env(SERVER_HOST)
} else {
    set host "103.56.206.89"
}
if {[info exists env(SERVER_USER)]} {
    set user $env(SERVER_USER)
} else {
    set user "efi"
}
spawn ssh -o StrictHostKeyChecking=no $user@$host "echo $pass | sudo -S $cmd"
expect {
    -nocase "password:" {
        send "$pass\r"
        exp_continue
    }
    eof
}
