#!/usr/bin/expect -f
set timeout 60
set src [lindex $argv 0]
set dst [lindex $argv 1]
if {[info exists env(SERVER_HOST)]} {
    set host $env(SERVER_HOST)
} else {
    set host "103.56.206.89"
}
if {[info exists env(SERVER_USER)]} {
    set user $env(SERVER_USER)
} else {
    set user "efi"
}
if {[info exists env(SERVER_PASS)]} {
    set pass $env(SERVER_PASS)
} else {
    set pass ""
}
spawn scp -o StrictHostKeyChecking=no $src $user@$host:$dst
expect {
    -nocase "password:" {
        send "$pass\r"
        exp_continue
    }
    eof
}
